name: Build Android Production AAB ubuntu job - in mode test use staging 

on: [workflow_dispatch]

jobs:
  build_code:
    name: Check out & Setup Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK Version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: flutter Action
        uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: '3.7.5'
          channel: 'stable'
          cache: true

      - name: Creating the key.properties file
        - shell: bash
          env:
            FLAVOR: ${{ secrets.FLAVOR }}
          run: |
            echo "$FLAVOR" >> lib/flavor.dart

      - name: Bumblebee Transform AAB
        run: flutter build apk